org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.224
loader_version_range=[1,)

mod_id=tianshu_libs
mod_name=Tianshu Libraries
mod_license=LGPL-3.0
mod_version=1.0.1
mod_group_id=com.rheinmetal.tianshu.libs
