modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Native AI inference library for Tianshu mod.
Bundles llama.cpp (jjml), ONNX Runtime, Sherpa-ONNX, and SentencePiece.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
